package com.sunbeam.entities;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum City {
    DELHI("Delhi"),
    MUMBAI("Mumbai"),
    KOLKATA("Kolkata"),
    BANGALORE("Bangalore"),
    CHENNAI("Chennai"),
    HYDERABAD("Hyderabad"),
    PUNE("Pune"),
    AHMEDABAD("Ahmedabad"),
    SURAT("Surat"),
    LUCKNOW("Lucknow"),
    JAIPUR("Jaipur"),
    KANPUR("Kanpur"),
    MIRZAPUR("Mirzapur"),
    NAGPUR("Nagpur"),
    GHAZIABAD("Ghaziabad"),
    SUPAUL("Supaul"),
    VADODARA("Vadodara"),
    RAJKOT("Rajkot"),
    VISHAKHAPATNAM("Vishakhapatnam"),
    INDORE("Indore"),
    THANE("Thane"),
    BHOPAL("Bhopal"),
    PIMPRI_CHINCHWAD("Pimpri-Chinchwad"),
    PATNA("Patna"),
    BILASPUR("Bilaspur"),
    LUDHIANA("Ludhiana"),
    AGRA("Agra"),
    MADURAI("Madurai"),
    JAMSHEDPUR("Jamshedpur"),
    PRAYAGRAJ("Prayagraj"),
    NASIK("Nasik"),
    FARIDABAD("Faridabad"),
    MEERUT("Meerut"),
    JABALPUR("Jabalpur"),
    KALYAN("Kalyan"),
    VASAI_VIRAR("Vasai-Virar"),
    NAJAFGARH("Najafgarh"),
    VARANASI("Varanasi"),
    SRINAGAR("Srinagar"),
    AURANGABAD("Aurangabad"),
    DHANBAD("Dhanbad"),
    AMRITSAR("Amritsar"),
    ALIGARH("Aligarh"),
    GUWAHATI("Guwahati"),
    HOWRAH("Howrah"),
    RANCHI("Ranchi"),
    GWALIOR("Gwalior"),
    CHANDIGARH("Chandigarh"),
    HALDWANI("Haldwani"),
    VIJAYAWADA("Vijayawada"),
    JODHPUR("Jodhpur"),
    RAIPUR("Raipur"),
    KOTA("Kota"),
    BHAYANDAR("Bhayandar"),
    LONI("Loni"),
    AMBATTUR("Ambattur"),
    SALT_LAKE_CITY("Salt Lake City"),
    BHATPARA("Bhatpara"),
    KUKATPALLI("Kukatpalli"),
    DASARHALLI("Dasarahalli"),
    MUZAFFARPUR("Muzaffarpur"),
    OULGARET("Oulgaret"),
    NEW_DELHI("New Delhi"),
    TIRUVOTTIYUR("Tiruvottiyur"),
    PUDUCHERRY("Puducherry"),
    BYATARAYANPUR("Byatarayanpur"),
    PALLAVARAM("Pallavaram"),
    SECUNDERABAD("Secunderabad"),
    SHIMLA("Shimla"),
    PURI("Puri"),
    MURTAZABAD("Murtazabad"),
    SHRIRAMPUR("Shrirampur"),
    CHANDANNAGAR("Chandannagar"),
    SULTANPUR_MAZRA("Sultanpur Mazra"),
    KRISHNANAGAR("Krishnanagar"),
    BARAKPUR("Barakpur"),
    BHALSWA_JAHANGIRPUR("Bhalswa Jahangirpur"),
    NANGLOI_JAT("Nangloi Jat"),
    BALASORE("Balasore"),
    DALUPURA("Dalupura"),
    YELAHANKA("Yelahanka"),
    TITAGARH("Titagarh"),
    DAM_DAM("Dam Dam"),
    BANSBARIA("Bansbaria"),
    MADHAVARAM("Madhavaram"),
    ABBIGERI("Abbigiri"),
    BAJ_BAJ("Baj Baj"),
    GARHI("Garhi"),
    MIRPETA("Mirpeta"),
    NERKUNRAM("Nerkunram"),
    KENDRAPARHA("Kendraparha"),
    SIJUA("Sijua"),
    MANALI("Manali"),
    KANKURIA("Kankuria"),
    CHAKAPARA("Chakapara"),
    PAPPAKURICHCCHI("Pappakurichchhi"),
    HEROHALLI("Herohalli"),
    MADIPAKKAM("Madipakkam"),
    SABALPUR("Sabalpur"),
    BAURIA("Bauria"),
    SALUA("Salua"),
    CHIK_BANAVAR("Chik Banavar"),
    JALHALLI("Jalhalli"),
    CHINNASEKKADU("Chinnasekkadu"),
    JETHULI("Jethuli"),
    NAGTALA("Nagtala"),
    PAKRI("Pakri"),
    HUNASAMARANHALLI("Hunasamaranhalli"),
    HESARGHATTA("Hesarghetta"),
    BOMMAYAPALAIYAM("Bommayapalaiyam"),
    GUNDUR("Gundur"),
    PUNADIH("Punadih"),
    HARILADIH("Hariladih"),
    ALAWALPUR("Alawalpur"),
    MADNAIKANHALLI("Madnaikanhalli"),
    BAGALUR("Bagalur"),
    KADIGANAHALLI("Kadiganahalli"),
    KHANPUR_ZABTI("Khanpur Zabti"),
    MAHULI("Mahuli"),
    ZEYADAH_KOT("Zeyadah Kot"),
    ARSHAKUNTI("Arshakunti"),
    MIRCHI("Mirchi"),
    SONUDIH("Sonudih"),
    BAYANDHALLI("Bayandhalli"),
    SONDEKOPPA("Sondekoppa"),
    BABURA("Babura"),
    MADAVAR("Madavar"),
    KADABGERI("Kadabgeri"),
    NANMANGALAM("Nanmangalam"),
    TALIGANJA("Taliganja"),
    TARCHHA("Tarchha"),
    BELGHARIA("Belgharia"),
    KAMMANHALLI("Kammanhalli"),
    AMBAPURAM("Ambapuram"),
    SONNAPPANHALLI("Sonnappanhalli"),
    KEDIHATI("Kedihati"),
    DODDAJIVANHALLI("Doddajivanhalli"),
    SIMLI_MURARPUR("Simli Murarpur"),
    SONAWAN("Sonawan"),
    DEVANANDAPUR("Devanandapur"),
    TRIBENI("Tribeni"),
    HUTTANHALLI("Huttanhalli"),
    NATHUPUR("Nathupur"),
    BALI("Bali"),
    VAJARHALLI("Vajarhalli"),
    ALIJA_KOTLA("Alija Kotla"),
    SAINO("Saino"),
    SHEKHPURA("Shekhpura"),
    CACHOHALLI("Cachohalli"),
    ANDHERI("Andheri"),
    NARAYANPUR_KOLA("Narayanpur Kola"),
    GYAN_CHAK("Gyan Chak"),
    KASGATPUR("Kasgatpur"),
    KITANELLI("Kitanelli"),
    HARCHANDI("Harchandi"),
    SANTOSHPUR("Santoshpur"),
    BENDRAVADI("Bendravadi"),
    KODAGIHALLI("Kodagihalli"),
    HARNA_BUZURG("Harna Buzurg"),
    MAILANHALLI("Mailanhalli"),
    SULTANPUR("Sultanpur"),
    ADAKIMARANHALLI("Adakimaranhalli");

    private final String value;

    City(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonCreator
    public static City fromValue(String value) {
        for (City city : values()) {
            if (city.value.equalsIgnoreCase(value)) {
                return city;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
